kind: Deployment
apiVersion: apps/v1
metadata:
  name: workload-example
  namespace: workload-example
  labels:
    app: workload-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-example
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: workload-example
    spec:
      restartPolicy: Always
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: workload-example
          env:        
            - name: MESSAGE
              valueFrom:
                secretKeyRef:
                  name: workload-example
                  key: MESSAGE
          securityContext: {}
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            quay.io/rciots/workload-example:latest
      dnsPolicy: ClusterFirst